# Generated by Django 3.2.13 on 2022-06-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50, null=True)),
                ('invoice_no', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'customer_reg',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.BigIntegerField(null=True)),
                ('item_name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'item_master',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=50)),
                ('invoice_no', models.BigIntegerField()),
                ('item_name', models.CharField(max_length=50, null=True)),
                ('quantity', models.BigIntegerField(null=True)),
                ('unit', models.BigIntegerField(null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.master')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
